// CONSTRUCTOR 

// MEMORY ALLOCATION HAPPENS WHEN CONSTRUCTOR IS CALLED 
// (CLASS DOES NOT OCCUPY A LOT OF SPACE IN THE MEOMORY BUT THE OBJECTS DO)
// (OR YE MEMORY KI ALLOCATION TBB HOTI HAI TBB CONSTRUCTOR KO CALL JAYE EITHER COMPILER VALA OR JO HUMNE BNAYA HAI)
// (TO YE OBJECTS KO MEMORY ALLOCATE KRNE KA KAAM IS CONDTRUCTOR KA)  

// 3 TYPES OF CONSTRUCTOR:
// 1) NON PARAMETERISED CONSTRUCTOR  ---> JESE KI JIN FUNCTION KE KOI PARAMETER NA HO
// 2) PARAMETERISED CONSTRUCTOR  --->  JESE KI JIN FUNCTION KE PARAMETERS HO
// 3) COPY CONSTRUCTOR

// WE CAN MAKE 1 OR MORE CONSTRUCTOR IN A CLASS GIVEN KI HARR CONSTRUCTOR KE PARAMETERS ALG HO
// (KUCH BHI FARK HO BSS EK DUM SAME NA HO .. SIRF DATA TYPES BHI ALG HAI TO CHLEGA)

/// CONSTRUCTOR OVERLOADING WHEN THERE ARE MORE THAN ONE CONSTRUCTOR IN A CLASS
/// (IT IS AN EXAMPLE OF POLYMORPHISM)