// CONSTRUCTOR 

// ITS A SPECIAL METHOD / MEMBER FUNCTION THAT IS INVOKED AUTOMATICALLY AT TIME OF OBJECT CREATION 
// (REMEMBER MEMBER FUNCTION OF A CLASS IS CALLED AS METHOD ALSO)

// USED FOR INITIALISATION OF DATA MEMBERS
// (AGR HUME PHLE HI KISI DATA MEMBER KI VALUE KO BY DEFAULT SAME SET KRNA HAI SBKE LIYE)

// AGAR HUM CONSTRUCTOR NHI BNATE TO COMPILER KHUD CONSTRUCTOR BNA DETA HAI
// PR JBB HUM CONSTRUCTOR BNATE HAI TBB BY DEFAULT VALA CONSTRUCTOR NHI CHLTA

// IT HAS SAME NAME AS CLASS

// IT HAS NO RETURN TYPE (NOT EVEN VOID)

// ONLY CALLED ONCE (AUTOMATICALLY) , AT OBJECT CREATION
// (HAR OBJECT KE LIYE EK-EK BAAR CALL HOGA)// (AGR 3 OBJECTS BNAYE OF A CLASS THEN 3 TIMES CONSTRUCTOR CALL HOGA FOR EACH CLASS)  

// EK HI BAAR CALL HOGA CONSTRUCTOR FOR EACH OBJECT

// KYUNKI MAIN FUNCTION SE AUTOMATICALLY CONSTRUCTOR KO CALL JARA HAI TO USKO HMESHA PUBLIC MEIN BNANA HAI 
// (NOT IN PRIVATE)




